LX_CLASS(AABB, LXObject)
LX_CLASS(BoundingBoxComponent, Component)
LX_CLASS(Camera, LXObject)
LX_CLASS(Component, LXObject)
LX_CLASS(CPUBuffers, LXObject)
LX_CLASS(CullingOptions, LXObject)
LX_CLASS(CurlRequest, LXObject)
LX_CLASS(DataInspectorTool, EditorTool)
LX_CLASS(DebugRenderer, LXObject)
LX_CLASS(DefaultTextureHolder, LXObject)
LX_CLASS(DisplayOptions, LXObject)
LX_CLASS(Editor, LXObject)
LX_CLASS(EditorOptions, LXObject)
LX_CLASS(EditorTool, LXObject)
LX_CLASS(EngineSettings, LXObject)
LX_CLASS(EngineStats, LXObject)
LX_CLASS(Entity, LXObject)
LX_CLASS(Framebuffer, LXObject)
LX_CLASS(GUI, LXObject)
LX_CLASS(Heightfield, LXObject)
LX_CLASS(ImguiManager, LXObject)
LX_CLASS(ImguiPointerDisplay, LXObject)
LX_CLASS(InputHandler, LXObject)
LX_CLASS(LightingOptions, LXObject)
LX_CLASS(LXObject, None)
LX_CLASS(MainWindow, LXObject)
LX_CLASS(Material, LXObject)
LX_CLASS(MaterialTool, EditorTool)
LX_CLASS(Mesh, LXObject)
LX_CLASS(Model, LXObject)
LX_CLASS(Node, OSMElement)
LX_CLASS(ObjectTool, EditorTool)
LX_CLASS(OSMAttribute, LXObject)
LX_CLASS(OSMDataProcessor, LXObject)
LX_CLASS(OSMDataProcessorSettings, LXObject)
LX_CLASS(OSMElement, LXObject)
LX_CLASS(OSMElementComponent, Component)
LX_CLASS(OSMElementTypeData, LXObject)
LX_CLASS(OSMElementTypeDataStore, LXObject)
LX_CLASS(OSMTool, EditorTool)
LX_CLASS(PickingTool, EditorTool)
LX_CLASS(PostEffects, LXObject)
LX_CLASS(RenderDataManager, LXObject)
LX_CLASS(Renderer, LXObject)
LX_CLASS(RenderingStats, LXObject)
LX_CLASS(Sector, LXObject)
LX_CLASS(SectorGraphicalData, LXObject)
LX_CLASS(SectorTool, EditorTool)
LX_CLASS(Serializer2, LXObject)
LX_CLASS(SerializerInputVariable, LXObject)
LX_CLASS(SunLight, LXObject)
LX_CLASS(TerrainTool, EditorTool)
LX_CLASS(TestComponentA, Component)
LX_CLASS(TestComponentB, Component)
LX_CLASS(Texture, LXObject)
LX_CLASS(Visual, Component)
LX_CLASS(Way, OSMElement)
LX_CLASS(World, LXObject)
LX_ENUM(DisplayMode)
LX_ENUM(EEditorTool)
LX_ENUM(GLPixelType)
LX_ENUM(GLPixelFormat)
LX_ENUM(ShaderFamily)
LX_ENUM(OSMElementType)
LX_ENUM(TerrainEditionMode)
