#pragma once

#define LX_LIMITS_INT_MIN INT_MIN
#define LX_LIMITS_INT_MAX INT_MAX

#define LX_LIMITS_FLOAT_MIN FLT_MIN
#define LX_LIMITS_FLOAT_MAX FLT_MAX

#define LX_LIMITS_DOUBLE_MIN DBL_MIN
#define LX_LIMITS_DOUBLE_MAX DBL_MAX