#pragma once

#define LX_LIMITS_UINT_MIN 0
#define LX_LIMITS_UINT_MAX UINT_MAX

#define LX_LIMITS_INT_MIN INT_MIN
#define LX_LIMITS_INT_MAX INT_MAX

#define LX_LIMITS_INT64_MIN LLONG_MIN
#define LX_LIMITS_INT64_MAX LLONG_MAX

#define LX_LIMITS_FLOAT_MIN FLT_MIN
#define LX_LIMITS_FLOAT_MAX FLT_MAX

#define LX_LIMITS_DOUBLE_MIN DBL_MIN
#define LX_LIMITS_DOUBLE_MAX DBL_MAX